# Generated by Django 3.2.2 on 2021-05-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=32)),
                ('uuid', models.CharField(max_length=32)),
                ('accessToken', models.CharField(max_length=32)),
                ('serverID', models.CharField(max_length=42)),
            ],
        ),
    ]
