# Generated by Django 3.2.2 on 2021-06-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='versions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=16)),
                ('changes', models.CharField(max_length=500)),
            ],
        ),
    ]
