# Generated by Django 3.2.2 on 2021-06-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mine', '0002_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='email',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players',
            name='verification',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
