# Generated by Django 3.2.2 on 2021-07-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mine', '0003_auto_20210618_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='web_tocken',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
