# Generated by Django 3.2.8 on 2021-10-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_web_token_players_webtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='nickname_token',
            new_name='nicknameToken',
        ),
        migrations.RenameField(
            model_name='players',
            old_name='password_token',
            new_name='passwordToken',
        ),
    ]
